name: CI

on:
  push:
    branches:
      - github-actions

jobs:
  # -------------------------------------------------------------
  # Using GitHub's API is not supported for push events
  # -------------------------------------------------------------
  # 
  # ----------------------------------------------------------------------------------------------
  # Using local .git history
  # ----------------------------------------------------------------------------------------------
  # Event `push`: Compare the preceding remote commit -> to the current commit of the main branch 
  # ----------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
          bundler-cache: true       
      - name: Get HTML file 
        id: changed-files-specific
        uses: tj-actions/changed-files@v40
        with:
          files: pages/manifest-ref-cai.md 
      - name: Run step if doc file(s) change
        if: steps.changed-files-specific.outputs.test_any_changed == true 
        run: bundle exec jekyll build
      - uses: actions/upload-pages-artifact@v1
        with:
            path: "_site/"
         
    
    
          
          
            
        
